@startuml CASE-1 payment
participant "Клиент ФЛ" as client_fl
participant web
participant "Клиент ЮЛ" as client_ul
participant "PrivatePersonAccount (ФП плательщика)" as fp_in
participant "BusinessAccount (ФП получателя)" as fp_out
participant "Сontract (ЦБ)" as cb

client_fl --> web: Зайти на платформу ЦБ 
web --> web: ПМ БР: \n1. Формирование fingerprint \n 2.Подписание ЭС \n3.Шифрование
web --> fp_in: Запрос возможности перевода C2B перевода ЦР
fp_in -> fp_in: Контроли, проверки баланса
fp -> cb: Запрос возможности перевода C2B перевода ЦР
cb -> cb: Контроли, фрод
cb -> cb: Формирование эталона ЭС, эталона Дайджеста PP
cb --> fp_in: Ответ на запрос возможности C2B перевода ЦР
fp_in --> web: Ответ на запрос возможности C2B перевода ЦР
web --> web: ПМ БР: Расшифрование, проверка ЭП
web -> web: ПМ БР: \n1. Формирование fingerprint \n 2.Подписание ЭС \n3.Шифрование \n4. Формирование дайджеста РР
web -> fp_in: Распоряжение клиента на перевод ЦР (C2B)
fp_in -> cb: Распоряжение клиента на перевод ЦР (C2B)
cb -> cb: Контроли
cb -> cb: Перевод ЦР
cb --> fp_in: Извещение Клиента - плательщика об исполнении переовда ЦР (C2B)
cb --> fp_out: Извещение Клиента - получателля об исполнении переовда ЦР (C2B)
fp_out ->  client_ul: Извещение Клиента - получателля об исполнении переовда ЦР (C2B)
client_ul -> client_ul: Расшифрование, проверка ЭП
fp_in -> web: Извещение Клиента - плательщика об исполнении переовда ЦР (C2B)
web -> web: Расшифрование, проверка ЭП
cb --> fp_out: Дополнительная информация к уведомлению получателя перевода
@enduml
