@startuml CASE-1 payment
participant "Клиент ФЛ" as client_fl
participant mobile
participant "Клиент ЮЛ" as client_ul
participant "ФП плательщика" as fp_in
participant "ФП получателя" as fp_out
participant "РОРД" as cb

... Оффлайн ...
client_fl -> mobile: Запрос на перевод
mobile -> mobile: Сохранение перевода до момента \nподключения к интернету \n(summ, address_ul)
mobile --> client_fl: Нотификация
... Онлайн ...
mobile -> fp_in: Отправить попытку транзакции
fp_in -> fp_in: Проверка счёта
alt На счету достаточно средств
    fp_in -> fp_in: Контроли, проверки баланса
    alt Если пользователь в чёрных списках или закончились лимиты
        mobile --> client_fl: Нотификация об отменённой транзакции
        fp_in -> fp_in: Отмена транзакции
    end
    fp_in -> cb: Запрос на перевод ЦР
    cb -> cb: Контроли, фрод
    cb -> cb: Перевод ЦР
    cb --> fp_in: Извещение Клиента - плательщика об исполнении переовда ЦР (C2B)
    fp_in --> mobile: Извещение Клиента - плательщика об исполнении переовда ЦР (C2B)
else Средств недостаточно
    mobile -> cb: Запрос на наличие соглашения об авто-свопе
    alt Если пользователь дал разрешение на своп
        fp_in -> fp_in: Блокировка фиата как залога
        fp_in -> cb: Перевод фиата в ЦР
        cb -> cb: Бёрн фиата и минт эквивалента в ЦР
        cb -> mobile: Перевод ЦР на кошелёк клиента
        mobile --> client_fl: Нотификация
    end
    else Если пользователь не дал разрешение на своп
        mobile -> cb: Запрос на выдачу кредита в ЦР
        fp_in -> cb: Перевод фиата в ЦР
        cb -> cb: Блокировка фиата как залога
        cb -> fp_in: Перевод ЦР на кошелёк клиента
        fp_in --> mobile: Извещение Клиента - плательщика об исполнении переовда ЦР (C2B)
        mobile --> client_fl: Нотификация
    end
end
fp_out -> client_ul: Извещение Клиента - получателля об исполнении переовда ЦР (C2B)
client_ul -> client_ul: Расшифрование, проверка ЭП
@enduml